"""empty message

Revision ID: bbc8c0e60a45
Revises: 
Create Date: 2021-06-17 08:54:00.021525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc8c0e60a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(length=10), nullable=True),
    sa.Column('car_description', sa.String(length=50), nullable=False),
    sa.Column('rental_cost', sa.Float(), nullable=True),
    sa.Column('number_orders', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_number')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('passport', sa.String(length=10), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.Column('number_orders', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passport')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(length=10), nullable=True),
    sa.Column('car_description', sa.String(length=50), nullable=False),
    sa.Column('client_passport', sa.String(length=10), nullable=True),
    sa.Column('date_rent', sa.DateTime(), nullable=False),
    sa.Column('rental_time', sa.Integer(), nullable=False),
    sa.Column('rental_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['car_number'], ['cars.car_number'], ),
    sa.ForeignKeyConstraint(['client_passport'], ['clients.passport'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('clients')
    op.drop_table('cars')
    # ### end Alembic commands ###
